name: Functions
on:
  workflow_dispatch:
jobs:
  Function:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: functions
        run: |
          echo "Format function ${{ format('Deploying {0} to {1}', 'MyApp', 'us-west-1') }}"
          echo "contains function ${{ contains('dev,qa,prod', 'prod') }}"
          echo "startsWith function ${{ startsWith(github.ref, 'refs/heads/main') }}"
          echo "endsWith ${{ endsWith(github.ref, '/main') }}"
          echo "join ${{ join(fromJson('["app1","app2"]'), ', ') }}"
          echo 'toJson ${{ toJson(github.event.head_commit) }}'
          echo "hashFiles ${{ hashFiles('README.md') }}"
    
  
